name: Auto-update TVBoxTG

on:
  schedule:
    - cron:  '0 */2 * * *'  # 每2小时执行一次
  workflow_dispatch:      # 允许手动触发

# 授予工作流必要的权限
permissions:
  contents: write
  actions: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 获取所有历史记录
          persist-credentials: true  # 保持凭据以便后续操作

      - name: Set up Git
        run: |
          git config --global user.name "wwz09"
          git config --global user.email "wwz5124@gmail.com"

      - name: Add upstream remote
        run: git remote add upstream "https://github.com/ls125781003/tvboxtg.git" || echo "Upstream remote already exists"

      - name: Fetch upstream
        run: git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout main  # 切换到要同步的分支
          # 尝试合并上游更改，如果有冲突则解决冲突
          git merge --no-edit upstream/main || (
            echo "检测到冲突，尝试自动解决..."
            # 使用上游版本覆盖冲突文件
            git checkout --theirs .
            git add .
            git commit -m "自动解决上游同步冲突"
          )

      - name: Push changes
        run: |
          # 尝试推送，如果失败则拉取最新代码后再次尝试
          git push origin main || (
            echo "推送失败，尝试拉取最新代码并重试..."
            git pull --rebase origin main
            git push origin main
          )

      - name: 触发URL替换工作流（如果需要）
        if: ${{ env.HAS_CHANGES == 'true' }}
        run: |
          echo "检测到代码变更，触发URL替换工作流..."
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{"event_type":"sync_upstream"}'